Completed classesandobjects exercises
reinis-kalbergs/codelex-exercises pull request #4
Opened 2022-03-08 21:21 UTC by reinis-kalbergs

2022-03-18 15:01 UTC, NilsKula requested changes
baigi labi

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise2/Car.java
> +        return calculateConsumption() > 15;
constant

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise3/FuelGauge.java
> +        this(0);
var bez šī, primatīvajiem ir default value

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise3/FuelGauge.java
> +        if (currentFuelAmount < 70)
constant
curly braces

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise3/Odometer.java
> +    public Odometer(int mileage) {
konstruktoru labāk kā pirmo pēc parametriem

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise3/Odometer.java
> +        if (mileage == 999999) {
constant

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise4/Movie.java
> +                count++;
šeit jau vari likt vilmas jaunāja array, nebūs otrs loop vjadzīgs

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise7/Dog.java
> +    public enum gender{
enumi ir tikpat kā klases, rakstība ar lielo burtu `Gender`

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercises/exercise7/Dog.java
> +        if (this.mother == null || possibleSibling.getMother() == null) return false; // No mothers found.
formatting: curly braces utt

2022-03-18 15:01 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/BankAccount.java
> +        this.balance = 0;
šo ar var izlaist

2022-04-10 06:38 UTC, janistumpelis approved these changes

2022-04-10 06:39 UTC, janistumpelis commented
@reinis-kalbergs vari mērdžot

2022-04-10 16:45 UTC, merged