Oop
reinis-kalbergs/codelex-exercises pull request #6
Opened 2022-03-22 17:38 UTC by reinis-kalbergs

2022-03-29 16:36 UTC, NilsKula requested changes

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/Car.java
> +        return yearOfManufacture == car.yearOfManufacture && Objects.equals(name, car.name) && Objects.equals(model, car.model) && Objects.equals(price, car.price) && Objects.equals(manufacturerList,
if you have to scroll to the left, the line is too long 😄
https://www.oracle.com/java/technologies/javase/codeconventions-indentation.html

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/CarService.java
> +        carsInService.remove(carToRemove);
remove jau kaut ko atgriež, ja elements nav

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/CarService.java
> +    public List<Car> getCarsBefore1999() {
varētu kā variable padot gadu

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/CarService.java
> +            if (car.getManufacturerList().contains(manufacturer))
šo varētu kā palīgmetodi `cars` klasē

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/Manufacturer.java
> +    final private String name;
private

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/Manufacturer.java
> +public class Manufacturer {
secība klasē

1. variables
2. constructor
3. getters/setters
4. methods

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/computers/Computer.java
> +    private String RAM;
caps lock only for constants

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/parcels/Parcel.java
> +        if (xLength > 300 || yLength > 300 || zLength > 300) {
constants, palīgmetodes

2022-03-29 16:36 UTC, NilsKula commented on src/main/java/io/codelex/oop/runners/Runner.java
> +        if (runTimeInMinutes <= ADVANCED.getMaximumTime() && runTimeInMinutes >= ADVANCED.getMinimumTime())
`if(isAdvanced())` for example

2022-03-29 20:09 UTC, reinis-kalbergs commented on src/main/java/io/codelex/oop/cars/Manufacturer.java
> +    final private String name;
es nesapratu par ko šeit ir domāts

2022-03-30 13:29 UTC, NilsKula commented on src/main/java/io/codelex/oop/cars/Manufacturer.java
> +    final private String name;
uj, vainīgs, izlasīju pirmo vārdu jau automātiski...
access modifier always first :smile:

2022-03-30 13:30 UTC, NilsKula approved these changes

2022-03-30 14:33 UTC, merged